"use client";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useCart } from "@/components/StoreProvider";
import { money, store } from "@/lib/store";
export default function Checkout(){const {items,subtotal,clear}=useCart();const router=useRouter();const [loading,setLoading]=useState(false);const [error,setError]=useState("");const shipping=useMemo(()=>subtotal===0?0:subtotal>=store.freeShippingThreshold?0:store.shippingFee,[subtotal]); const total=subtotal+shipping;
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!items.length)return;setLoading(true);setError("");const form=new FormData(e.currentTarget);const payload={customer:Object.fromEntries(form.entries()),items:items.map(x=>({id:x.product.id,quantity:x.quantity})),paymentMethod:"cash_on_delivery"};const res=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await res.json().catch(()=>({}));if(!res.ok){setError(body.error||"We could not place your order. Please contact support.");setLoading(false);return;}clear();router.push(`/order-success?order=${encodeURIComponent(body.orderId)}`)}
if(!items.length)return <section className="section container"><h1>Checkout</h1><div className="empty"><p>Your cart is empty.</p><Link href="/shop" className="button primary">Shop products</Link></div></section>;
return <section className="section container"><h1>Checkout</h1><p className="lead small">Review the full cost and purchase conditions before placing your order.</p><div className="checkout-grid"><form onSubmit={submit} className="checkout-form"><h2>Contact & delivery</h2><div className="form-grid"><label>Full name<input name="name" required autoComplete="name"/></label><label>Email<input type="email" name="email" required autoComplete="email"/></label><label>Phone<input name="phone" required autoComplete="tel"/></label><label>Country<input name="country" required defaultValue={store.country} autoComplete="country-name"/></label><label className="wide">Street address<input name="address" required autoComplete="street-address"/></label><label>City<input name="city" required autoComplete="address-level2"/></label><label>State / Region<input name="region" required autoComplete="address-level1"/></label><label>Postal code<input name="postalCode" required autoComplete="postal-code"/></label></div><h2>Payment</h2><div className="payment-box"><input type="radio" checked readOnly/> <div><strong>Cash on Delivery (COD)</strong><p>Pay the full order total when your parcel is delivered. No card details are required on this website.</p></div></div><label className="check"><input type="checkbox" name="termsAccepted" value="yes" required/> <span>I agree to the <Link href="/policies/terms">Terms & Conditions</Link> and acknowledge the <Link href="/policies/returns">Returns & Refunds Policy</Link>.</span></label>{error&&<p className="error">{error}</p>}<button className="button primary full" disabled={loading}>{loading?"Placing order…":"Place order"}</button></form><aside className="summary"><h2>Final total</h2>{items.map(x=><div key={x.product.id}><span>{x.product.title} × {x.quantity}</span><strong>{money(x.product.price*x.quantity)}</strong></div>)}<hr/><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Shipping</span><strong>{shipping===0?"Free":money(shipping)}</strong></div><div className="total"><span>Total due</span><strong>{money(total)}</strong></div><p className="fineprint">Estimated delivery: {store.shippingMinDays}–{store.shippingMaxDays} business days. Payment method: Cash on Delivery (COD).</p></aside></div></section>}
